version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contenedor_telematica_prod
    ports:
      - "80:5000"
    restart: always
    environment:
      - FLASK_ENV=production